--- #YAML:1.0
name:                Continuity-Monitor
version:             0.01
abstract:            monitor and inspect a Continuity server
license:             perl
author:              
    - Brock Wilcox <awwaiid@thelackthereof.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Continuity:                    0.996
    Coro::Generator:               0
    Devel::StackTrace::WithLexicals: 0.01
    Method::Signatures:            20081008
    Module::Refresh:               0
    Moose:                         0.58
    Moose::Exporter:               0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
